### ISSUE TITLE
Problem with building for aarch64

### ISSUE THREAD

**Issue by gaiar** [conda-forge/cython-blis-feedstock#1]
Issue:
Hi, I'm getting error messages when trying to build `cython-blis` on ARM64 machine.

```
    $BUILD_PREFIX/bin/aarch64-conda_cos7-linux-gnu-cc -DNDEBUG -g -fwrapv -O3 -Wall -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O3 -pipe -I$PREFIX/include -fdebug-prefix-map=${SRC_DIR}=/usr/local/src/conda/${PKG_NAME}-${PKG_VERSION} -fdebug-prefix-map=${PREFIX}=/usr/local/src/conda-prefix -DNDEBUG -D_FORTIFY_SOURCE=2 -O3 -fPIC -I/tmp/pip-req-build-gfljmg94/include -I/tmp/pip-req-build-gfljmg94/blis/_src/include/linux-generic -I$PREFIX/include/python3.7m -c blis/cy.c -o build/temp.linux-aarch64-3.7/blis/cy.o -std=c99
    aarch64-conda_cos7-linux-gnu-cc: error: blis/cy.c: No such file or directory
    aarch64-conda_cos7-linux-gnu-cc: fatal error: no input files
    compilation terminated.
    error: command '$BUILD_PREFIX/bin/aarch64-conda_cos7-linux-gnu-cc' failed with exit status 1

    ----------------------------------------
Command "/root/archiconda3/conda-bld/cython-blis_1556101308761/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-req-build-gfljmg94/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-zcxq8594/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-req-build-gfljmg94/

```

<br/>
Environment (<code>conda list</code>):
<details>

# packages in environment at /root/archiconda3:
#
# Name                    Version                   Build  Channel
anaconda-client           1.7.1                      py_0    gaiar
asn1crypto                0.24.0                py37_1003    archiarm
attrs                     19.1.0                     py_0    conda-forge
beautifulsoup4            4.7.0                 py37_1000    archiarm
bzip2                     1.0.6             h14c3975_1002    archiarm
ca-certificates           2018.4.16                     0    gaiar
certifi                   2018.11.29            py37_1000    archiarm
cffi                      1.11.5          py37h9745a5d_1001    archiarm
chardet                   3.0.4                 py37_1003    archiarm
click                     7.0                        py_0    conda-forge
clyent                    1.2.2                      py_1    gaiar
conda                     4.6.13                   py37_0    conda-forge
conda-build               3.16.3                   py37_0    archiarm
conda-env                 2.6.0                         1    archiarm
conda-verify              3.1.1                 py37_1000    conda-forge
cryptography              2.3.1           py37hb7f436b_1000    archiarm
decorator                 4.3.0                      py_0    gaiar
filelock                  3.0.4                      py_1    gaiar
future                    0.17.1                py37_1000    conda-forge
glob2                     0.6                      py37_0    archiarm
icu                       60.2              hf484d3e_1000    archiarm
idna                      2.8                   py37_1000    archiarm
ipython_genutils          0.2.0                      py_1    conda-forge
jinja2                    2.10                     py37_1    archiarm
jsonschema                3.0.0a3               py37_1000    archiarm
jupyter_core              4.4.0                      py_0    conda-forge
libarchive                3.3.3             h22067ca_1003    archiarm
libedit                   3.1.20170329      hf8c457e_1001    archiarm
libffi                    3.2.1             h38784ca_1005    archiarm
libgcc-ng                 7.3.0                h5c90dd9_0    c4aarch64
libiconv                  1.15              hda93590_1003    archiarm
liblief                   0.9.0                h1532aa0_0    conda-forge
libstdcxx-ng              7.3.0                h5c90dd9_0    archiarm
libxml2                   2.9.8             hb578d76_1005    archiarm
lz4                       2.1.6           py37h66ffc3c_1001    archiarm
lz4-c                     1.8.3             hf484d3e_1000    archiarm
lzo                       2.10              h14c3975_1000    archiarm
markupsafe                1.1.0           py37h14c3975_1000    archiarm
nbformat                  4.4.0                      py_1    gaiar
ncurses                   6.1                           1    gaiar
openssl                   1.0.2p            h14c3975_1002    archiarm
patchelf                  0.9               h38784ca_1002    archiarm
pip                       18.1                  py37_1000    archiarm
pkginfo                   1.4.2                    py37_1    archiarm
psutil                    5.4.8           py37h14c3975_1000    archiarm
py-lief                   0.9.0            py37hf484d3e_0    conda-forge
pycosat                   0.6.3           py37h14c3975_1001    archiarm
pycparser                 2.19                     py37_1    archiarm
pyopenssl                 18.0.0                py37_1000    archiarm
pyrsistent                0.14.9          py37h14c3975_1000    archiarm
pysocks                   1.6.8                 py37_1002    archiarm
python                    3.7.0                         0    gaiar
python-dateutil           2.7.3                      py_0    gaiar
python-libarchive-c       2.8                   py37_1004    archiarm
pytz                      2018.7                   py37_0    archiarm
pyyaml                    3.13            py37h14c3975_1001    archiarm
readline                  8.0                  h75b48e3_0    conda-forge
requests                  2.21.0                py37_1000    archiarm
ruamel_yaml               0.15.71         py37h14c3975_1000    archiarm
setuptools                40.6.3                   py37_0    archiarm
six                       1.12.0                py37_1000    archiarm
soupsieve                 1.9.1                    py37_0    conda-forge
sqlite                    3.26.0            hf8c457e_1000    archiarm
tk                        8.6.8                hbc83047_0    gaiar
tqdm                      4.28.1                   py37_0    archiarm
traitlets                 4.3.2                 py37_1000    archiarm
urllib3                   1.24.1                py37_1000    archiarm
wheel                     0.32.3                   py37_0    archiarm
xz                        5.2.4             h14c3975_1002    archiarm
yaml                      0.1.7             h14c3975_1001    archiarm
zlib                      1.2.11            h14c3975_1003    archiarm
zstd                      1.3.7             h0a35d5f_1000    archiarm
</details>

<br/>
Details about  <code>conda</code> and system ( <code>conda info</code> ):
<details>

```

     active environment : base
    active env location : /root/archiconda3
            shell level : 1
       user config file : /root/.condarc
 populated config files : /root/archiconda3/.condarc
                          /root/.condarc
          conda version : 4.6.13
    conda-build version : 3.16.3
         python version : 3.7.0.final.0
       base environment : /root/archiconda3  (writable)
           channel URLs : https://conda.anaconda.org/gaiar/linux-aarch64
                          https://conda.anaconda.org/gaiar/noarch
                          https://conda.anaconda.org/archiarm/linux-aarch64
                          https://conda.anaconda.org/archiarm/noarch
                          https://conda.anaconda.org/conda-forge/linux-aarch64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://conda.anaconda.org/nodefaults/linux-aarch64
                          https://conda.anaconda.org/nodefaults/noarch
                          https://conda.anaconda.org/c4aarch64/linux-aarch64
                          https://conda.anaconda.org/c4aarch64/noarch
          package cache : /root/archiconda3/pkgs
                          /root/.conda/pkgs
       envs directories : /root/archiconda3/envs
                          /root/.conda/envs
               platform : linux-aarch64
             user-agent : conda/4.6.13 requests/2.21.0 CPython/3.7.0 Linux/4.15.11-mainline-rev1 ubuntu/18.04.2 glibc/2.27
                UID:GID : 0:0
             netrc file : None
           offline mode : False

```
</details>

Here is the build.sh file I'm using

```#!/usr/bin/env bash

export BLIS_COMPILER="$CC"
export MAKEFLAGS="-j${CPU_COUNT}"

if [[ "$(uname)" == "Linux" ]]; then
    BLIS_ARCH=generic $PYTHON -m pip install . --no-deps
else
    $PYTHON -m pip install . --no-deps -vv
fi```

**Comment by gaiar** [comment]
Non-modified build.sh

```
    $BUILD_PREFIX/bin/aarch64-conda_cos7-linux-gnu-cc -c /tmp/pip-req-build-3nz_eiud/blis/_src/kernels/zen/1/bli_amaxv_zen_int.c -o /tmp/tmpnp8z9b_j/bli_amaxv_zen_int.o -O3 -mavx2 -mfma -mfpmath=sse -march=core-avx2 -fPIC -std=c99 -D_POSIX_C_SOURCE=200112L -DBLIS_VERSION_STRING="0.5.0-6" -DBLIS_IS_BUILDING_LIBRARY -Iinclude/linux-x86_64 -I./frame/3/ -I./frame/ind/ukernels/ -I./frame/1m/ -I./frame/1f/ -I./frame/1/ -I./frame/include -I/tmp/pip-req-build-3nz_eiud/blis/_src/include/linux-x86_64
    aarch64-conda_cos7-linux-gnu-cc: error: unrecognized command line option '-mavx2'
    aarch64-conda_cos7-linux-gnu-cc: error: unrecognized command line option '-mfma'
    aarch64-conda_cos7-linux-gnu-cc: error: unrecognized command line option '-mfpmath=sse'
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-req-build-3nz_eiud/setup.py", line 266, in <module>
        'Topic :: Scientific/Engineering'
      File "$PREFIX/lib/python3.7/site-packages/setuptools/__init__.py", line 143, in setup
        return distutils.core.setup(**attrs)
      File "$PREFIX/lib/python3.7/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "$PREFIX/lib/python3.7/distutils/dist.py", line 966, in run_commands
        self.run_command(cmd)
      File "$PREFIX/lib/python3.7/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "$PREFIX/lib/python3.7/distutils/command/build_ext.py", line 340, in run
        self.build_extensions()
      File "/tmp/pip-req-build-3nz_eiud/setup.py", line 105, in build_extensions
        objects = self.compile_objects(compiler.split('-')[0], arch, OBJ_DIR)
      File "/tmp/pip-req-build-3nz_eiud/setup.py", line 184, in compile_objects
        objects.append(self.build_object(env=env, **spec))
      File "/tmp/pip-req-build-3nz_eiud/setup.py", line 198, in build_object
        subprocess.check_call(command, cwd=BLIS_DIR)
      File "$PREFIX/lib/python3.7/subprocess.py", line 347, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['$BUILD_PREFIX/bin/aarch64-conda_cos7-linux-gnu-cc', '-c', '/tmp/pip-req-build-3nz_eiud/blis/_src/kernels/zen/1/bli_amaxv_zen_int.c', '-o', '/tmp/tmpnp8z9b_j/bli_amaxv_zen_int.o', '-O3', '-mavx2', '-mfma', '-mfpmath=sse', '-march=core-avx2', '-fPIC', '-std=c99', '-D_POSIX_C_SOURCE=200112L', '-DBLIS_VERSION_STRING="0.5.0-6"', '-DBLIS_IS_BUILDING_LIBRARY', '-Iinclude/linux-x86_64', '-I./frame/3/', '-I./frame/ind/ukernels/', '-I./frame/1m/', '-I./frame/1f/', '-I./frame/1/', '-I./frame/include', '-I/tmp/pip-req-build-3nz_eiud/blis/_src/include/linux-x86_64']' returned non-zero exit status 1.
    Running setup.py install for blis: finished with status 'error'
Cleaning up...
  Removing source in /tmp/pip-req-build-3nz_eiud
Removed build tracker '/tmp/pip-req-tracker-8ygod8zi'
Command "/root/archiconda3/conda-bld/cython-blis_1556108910877/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-req-build-3nz_eiud/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" build_ext -lrt install --record /tmp/pip-record-k2ijvahz/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-req-build-3nz_eiud/

```

**Comment by adrianeboyd** [comment]
I'm not exactly sure what was causing the original error, but I hope these are fixed in recent releases. As of v0.4.1 there are now `linux-aarch64` packages, too. As a note, if you're compiling you will need gcc 9 to compile for some of the specific architectures.
